### ISSUE TITLE
do "unknown" and "other" have the same color code?

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#101]
they look similar but please check

<img width="388" alt="Screen Shot 2022-02-11 at 12 29 00 PM" src="https://user-images.githubusercontent.com/41168017/153549356-0661ee14-164d-4412-b5b3-a4bccc47143b.png">

**Comment by mohitkharb** [comment]
yes @priyamvadatrivedi , I wanted to give greyish colors to both, right now its the same. Should I lighten the gradient for other or unknown?

**Comment by priyamvadatrivedi** [comment]
yes @mohitkharb. different colors/shades please.

**Comment by priyamvadatrivedi** [comment]
thanks!
