### ISSUE TITLE
Select top-3 parties by default

### ISSUE THREAD

**Issue by hangal** [tcpd/LokDhaba_JS#18]
it's odd that when i select a viz, nothing is shown until i check some parties.
can we show the top-N parties (N=3 or 5) 
The top-N can be defined as most votes in the most recent assembly.

![image](https://user-images.githubusercontent.com/1018175/71802261-3a965080-3083-11ea-9687-ee5addeea15e.png)

**Comment by hangal** [comment]
Similarly for browse-data and maps, last assembly can be auto-selected.

**Comment by mohitkharb** [comment]
resolved in commit 4a10fdee8401d8

**Comment by srishti-gupta-me** [comment]
![image](https://user-images.githubusercontent.com/46262561/147804239-acbac9a5-a39e-4e52-85aa-323bbcd714bd.png)

For visualizations at Party Level (Visualize category) the charts and maps have pre-selected values. The attached image is an example.
