### ISSUE TITLE
20210001: Andhra and Telangana Constituency Selection

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/LokDhaba_JS#54]
1. The constituencies in the map selected are wrong, upon selecting the checkbox _Show AC segment wise results_ for Andhra Pradesh and Telangana. 
2. As of now Telangana and Andhra Pradesh are separated for 2009, 2014, and 2019. 

http://103.7.128.220:3001/data-vis?et=GE&st=Andhra_Pradesh&var=ConstMap&viz=winnerCasteMap&an=17
http://103.7.128.220:3001/data-vis?et=GE&st=Andhra_Pradesh&var=ConstMap&viz=winnerCasteMap&an=17&seg=true

**Comment by mohitkharb** [comment]
updated on LD.

**Comment by srishti-gupta-me** [comment]
![image](https://user-images.githubusercontent.com/46262561/150074939-df8ef5a1-3b55-486e-8c6d-3d2487d0833b.png)
![image](https://user-images.githubusercontent.com/46262561/150075009-c5f054f6-1797-4f92-9c8f-b8d1f77ff0f9.png)

Terrority is marked rightly for both.
