### ISSUE TITLE
20210006: State Names need alphabetical order

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/LokDhaba_JS#59]
Lakshwadeep, Telangana, and Mysore in the last in the State Filter.

**Comment by mohitkharb** [comment]
@kkkarnav  : sort AE_States and GE_States in ComponentDidMount function in DataVisualization.js

**Comment by mohitkharb** [comment]
updated LD

**Comment by srishti-gupta-me** [comment]
The state names in the dropdown are sorted
