### ISSUE TITLE
20210007: Colors not loading for AE winners by party map

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/LokDhaba_JS#60]
https://lokdhaba.ashoka.edu.in/data-vis?et=AE&st=Andhra_Pradesh&var=PartyStats&seg=true&viz=winnerMap&opt=INC%2CIND%2CINC%28I%29%2CJNP%2CTDP%2CYSRCP&an=15

![image](https://user-images.githubusercontent.com/46262561/147812077-2b6ee345-1ece-422b-ad49-657709d443cd.png)

**Comment by mohitkharb** [comment]
resolved in commit ec89f93d979a9938f5de44312d62df789ab090d5

**Comment by srishti-gupta-me** [comment]
Working 

https://lokdhaba.ashoka.edu.in/data-vis?et=AE&st=Gujarat&var=PartyStats&viz=winnerMap&an=13
