### ISSUE TITLE
20210009: Candidate level charts not loading for GE

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/LokDhaba_JS#62]
Lok Dhaba Viz → Election: Lok Sabha, Visualize: Candidate Level, Visualization: all Charts, except Chart: Candidates contested/deposit lost→ not developing 

https://lokdhaba.ashoka.edu.in/data-vis?et=GE&st=Gujarat&var=Candidate&viz=rerunningCandidates&an=17&opt=RecontestingCandidatespct&seg=true

**Comment by mohitkharb** [comment]
resolved in commit ec89f93d979a9938f5de44312d62df789ab090d5

**Comment by srishti-gupta-me** [comment]
seg==true in the above link created issues. This condition is used to penetrate by changes made previously while filtering. Now issue is resolved.
