### ISSUE TITLE
20210010: AE voter turnout map colors not loading

### ISSUE THREAD

**Issue by srishti-gupta-me** [tcpd/LokDhaba_JS#63]
https://lokdhaba.ashoka.edu.in/data-vis?et=AE&st=Bihar&var=Turnout&viz=voterTurnoutMap&an=17&opt=male%2Cfemale%2Ctotal&seg=true

Similar to the git issue 20210007.

**Comment by mohitkharb** [comment]
The issue here is because of the "seg=true" parameter in the url. I am working on a solution that will resolve this. Will be done next week.

**Comment by mohitkharb** [comment]
resolved in commit ec89f93d979a9938f5de44312d62df789ab090d5

**Comment by srishti-gupta-me** [comment]
Issue resolved. The seg=true used to penetrate the link from previous changes. However, that's been changed.
