### ISSUE TITLE
extra space in title of affidavit charts

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#67]
it shows as: Professions of winners in  Assam Lok Sabha
it should be: Professions of winners in Assam Lok Sabha

delete the second space between "in" and "Assam"/state name

**Comment by mohitkharb** [comment]
I dont see an extra space in the title.

**Comment by mohitkharb** [comment]
happening when loading from URL and Assembly number is not set.

**Comment by priyamvadatrivedi** [comment]
cool
