### ISSUE TITLE
ADR data - blank and other values

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#70]
So we have "Other and Unspecified" --> can this be only "Other"?

"Unspecified" should be used for when the cells are blank. Instead of "0", we should have "Unspecified" which means no information.

**Comment by mohitkharb** [comment]
Keeping "unknown" for missing data values.

**Comment by blusoulna** [comment]
Currently "Other and Unspecified" has both blanks and "Other" professions (like household) Should we just disaggregate?

**Comment by priyamvadatrivedi** [comment]
yes.  "blank" should be "unspecified" or "unknown". everything else will be "other"
