### ISSUE TITLE
ordering the values in the legend

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#71]
occupation --> alphabetically
education --> low to high

**Comment by mohitkharb** [comment]
education levels : 
10th Pass, 12th Pass, 5th Pass, 8th Pass, Doctorate, Graduate, Graduate Professional, Literate, Not Given, Others, Post Graduate, Illiterate

**Comment by mohitkharb** [comment]
resolved in commit 5e546f1

**Comment by priyamvadatrivedi** [comment]
looks good. thanks MK!
