### ISSUE TITLE
problematic category in ADR occupation

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#80]
why do we have "government"? as those in the government cannot contest without giving up their jobs

**Comment by blusoulna** [comment]
So subcategories includes aanganwadi workers, but the rest should probably be former government.. I'll club with that
What should I be putting aanganwadi under? Education or Social Work?

**Comment by blusoulna** [comment]
Put Aanganwadi under Social Work
