### ISSUE TITLE
what is the 0 in the ADR education categories?

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#84]
if blank, then put unspecified

**Comment by mohitkharb** [comment]
Unspecified or Unknown @priyamvadatrivedi ?

**Comment by mohitkharb** [comment]
Updated lokdhaba data on tcpd_data repository, which should resolve this.

**Comment by priyamvadatrivedi** [comment]
mohit, what did you change this to? i see "unknown" in education. is it the same as "blank"?

**Comment by mohitkharb** [comment]
yes, I converted all blanks to "unknown"
