### ISSUE TITLE
width of bar in ADR profession and education chart when there are 1-3 parties

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#85]
can the width of the bar be made narrower? or a standard bar width selected so its constant regardless of the number of parties?

<img width="852" alt="Screen Shot 2022-01-25 at 10 01 24 PM" src="https://user-images.githubusercontent.com/41168017/151018831-4977bec1-6aca-4b90-9e6e-8842d1eadfd8.png">

**Comment by mohitkharb** [comment]
looks like this now (made it 0.4 times the column width
![newplot (18)](https://user-images.githubusercontent.com/1709862/151554110-6701110b-a8a2-40cb-a551-04e5f9eda609.png)

**Comment by priyamvadatrivedi** [comment]
looks good. thanks MK!
