### ISSUE TITLE
colors across ADR education charts

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#95]
can the colors be fixed for each value in the education variable? currently they change by year

**Comment by mohitkharb** [comment]
@priyamvadatrivedi : do we standardize colors for profession classes as well? (there are 19 classes right now)

**Comment by priyamvadatrivedi** [comment]
yes @mohitkharb that would be good

**Comment by priyamvadatrivedi** [comment]
cool. thanks!
