### ISSUE TITLE
ADR education - "not given" and "unknown" need to be combined

### ISSUE THREAD

**Issue by priyamvadatrivedi** [tcpd/LokDhaba_JS#96]
there is also a "not given" value
<img width="722" alt="Screen Shot 2022-02-02 at 6 43 57 AM" src="https://user-images.githubusercontent.com/41168017/152077918-57dc39f1-70b7-4a67-bdaf-dc1746537042.png">

**Comment by blusoulna** [comment]
Not Given has been clubbed with Unknown

**Comment by blusoulna** [comment]
This has been done

**Comment by priyamvadatrivedi** [comment]
thanks!
